apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: h3f7aapu3-go 
  janus-idp.io/tekton: h3f7aapu3-go
  backstage.io/kubernetes-id: h3f7aapu3-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h3f7aapu3-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  